/**:
  ros__parameters:
    feature_extract_enable: false
    point_filter_num: 4
    max_iteration: 3
    filter_size_surf: 0.5
    filter_size_map: 0.5
    cube_side_length: 1000.0
    runtime_pos_log_enable: false
    map_file_path: "./test.pcd"

    common:
        lid_topic:  "/cpr_a200_0000/sensors/lidar3d_0/points"
        imu_topic:  "/cpr_a200_0000/sensors/imu_0/data"
        time_sync_en: false         
        time_offset_lidar_to_imu: 0.0 

    preprocess:
        lidar_type: 5                # 5: Generic w/ PC2 (Trick to bypass AVIA CustomMsg check and use default_handler)
        scan_line: 16
        scan_rate: 10                
        timestamp_unit: 2            # 
        blind: 0.5

    mapping:
        acc_cov: 0.1
        gyr_cov: 0.1
        b_acc_cov: 0.0001
        b_gyr_cov: 0.0001
        fov_degree:    360.0
        det_range:     100.0
        extrinsic_est_en: false      
        extrinsic_T: [ 0.0, 0.0, 0.3] 
        extrinsic_R: [ 1., 0., 0., 
                       0., 1., 0., 
                       0., 0., 1.]

    publish:
        path_en:  true
        scan_publish_en:  true       
        dense_publish_en: true       
        scan_bodyframe_pub_en: true  

    pcd_save:
        pcd_save_en: true
        interval: -1                 
